<html>
<body>
<h2>Hello World!</h2>
</body>
</html>

//programm or technology required to make a web application, work logically i.e., connect to database that means get a dynamic response
//server will take the request where there will be logic to perform actions and this servlet works on it.
//static- a file will be in server and we will get it.
//dynamic- the data will not be in server, we go to database fetch them work on logic and get the response.
//or generating a file through the input from the user.
//or generated by the servlet.
//404 error - when the requested file is not found
//implement servlet- to use sevlet properties in java class
